# 1) align a 10X library onto all the assembly versions
# (I can use the BAM file generated by Longranger align for the coverage analysis for lycPyr6)

cd /proj/uppstore2018073/private/Valentina/lycPyr/Intermediate/Validation

/proj/uppstore2018073/private/Valentina/lycPyr/Intermediate/Exonerate

#!/bin/bash -l
#SBATCH -J VALIDATION_ALIGN_lycPyrIL
#SBATCH -o VALIDATION_ALIGN_lycPyrIL.output
#SBATCH -e VALIDATION_ALIGN_lycPyrIL.error
#SBATCH --mail-user valentina.peona90@gmail.com
#SBATCH --mail-type=ALL                           
#SBATCH -t 72:00:00                           
#SBATCH -A snic2019-8-79
#SBATCH -p core
#SBATCH -n 20

ml bioinfo-tools longranger/2.2.2

FASTA=lycPyrIL

cd /proj/uppstore2018073/private/Valentina/lycPyr/Intermediate/Validation/References

longranger mkref $FASTA.fasta

REF=/proj/uppstore2018073/private/Valentina/lycPyr/Intermediate/Validation/References/refdata-$FASTA
READS=/proj/sllstore2017073/private/BirdsOfParadise/lycPyr_10XG/H5JJHALXX/outs/fastq_path/A_Suh_16_01/Sample_P6156_102
SAMPLE=P6156_102

cd /proj/uppstore2018073/private/Valentina/lycPyr/Intermediate/Validation/

longranger align --id=lycPyrIL --sample=$SAMPLE --reference=$REF --fastqs=$READS

#!/bin/bash -l
#SBATCH -J VALIDATION_PROPER
#SBATCH -o VALIDATION_PROPER.output
#SBATCH -e VALIDATION_PROPER.error
#SBATCH --mail-user valentina.peona90@gmail.com
#SBATCH --mail-type=ALL                           
#SBATCH -t 12:00:00                           
#SBATCH -A snic2020-14-57
#SBATCH -p core
#SBATCH -n 4

cd /proj/uppstore2018073/private/Valentina/lycPyr/Intermediate/Validation/

ml bioinfo-tools samtools/1.10

#ls -d * | grep '^lyc' > list_dir

BAM=possorted_bam.bam

for DIR in $( cat list_dir )
do
 cd $DIR/outs/
 samtools stats -f 0x2 $BAM > $BAM.proper
 cd ../..
done
